# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    agenturkopfnuss\ContaoElementGroupFlex\:
        resource: '../src'
        exclude: '../src/{ContaoManager,DependencyInjection,Resources/contao/dca/*,Resources/contao/languages/*/*,Resources/contao/config/*}'

    agenturkopfnuss\ContaoElementGroupFlex\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']