services:
    _defaults:
        autowire: true
        autoconfigure: true

    agenturkopfnuss\ContaoElementGroupFlex\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}